name: AUTOMATED - CTFd sync
# Controls when the action will run. 
on:
  # Allows you to run this workflow automatically from the push event to `main` branch
  push:
    # paths:
    #   - 'challenges/**'
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install ctfcli
        run: |
          python -m pip install --upgrade pip
          pip install ctfcli
      - name: Set up ctfcli config
        run: |
          CONFIG="[config]\n
                  url = ${{ secrets.CTFD_URL }}\n
                  access_token = ${{ secrets.CTFD_TOKEN }}\n
                  \n
                  [challenges]\n"
          echo -e $CONFIG > .ctf/config
      - name: Install and sync challenges
        run: |
          shopt -s globstar
          for i in **/challenge.yml; do 
            CHAL_DIR=$(dirname $i)
            echo "SYNCING CHALLENGE TO CTFd: $CHAL_DIR"
            # Try installing first, if already exists, sync will update it
            ctf challenge install $CHAL_DIR
            ctf challenge sync $CHAL_DIR
            if [ $? == 1 ]; then
              echo "::warning::Error syncing challenge $CHAL_DIR"
            fi
          done
        shell: bash
